# Generated by Django 5.2.11 on 2026-02-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_calendar_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
