# Generated by Django 5.2.11 on 2026-02-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_force_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='resource_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='resource_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
