# Generated by Django 5.2.11 on 2026-03-03 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_partner_phone_alter_partner_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovator',
            name='language1',
        ),
        migrations.RemoveField(
            model_name='innovator',
            name='language2',
        ),
        migrations.RemoveField(
            model_name='innovator',
            name='language3',
        ),
        migrations.AddField(
            model_name='innovator',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='innovators', to='core.idea'),
        ),
    ]
