# Generated by Django 5.2.11 on 2026-03-12 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_message_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founder_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FounderProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(choices=[('Ideation', 'Ideation'), ('MVP', 'MVP'), ('Seed', 'Seed'), ('Scaling', 'Scaling'), ('Series A', 'Series A')], default='Ideation', max_length=50)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.founder')),
            ],
            options={
                'indexes': [models.Index(fields=['founder'], name='core_founde_founder_29fc67_idx'), models.Index(fields=['stage'], name='core_founde_stage_054448_idx')],
            },
        ),
    ]
